#!/bin/bash
INSTALLDIR=${1:-$HOME}
FULLPATH=$(readlink -f $0)
INCPATH=${FULLPATH%/*}

. $INCPATH/install_func.sh

menu

case $editor in
    1) install_vim ;;
    2) install_neovim ;;
    0) exit 0 ;;
    *) echo -e $red"Not a valid option"$clear; menu ;;
esac

ln -s $PWD/.bash_aliases $INSTALLDIR/.bash_aliases 2> /dev/null
ln -s $PWD/.tmux.conf $INSTALLDIR/.tmux.conf 2> /dev/null

cat $PWD/.bashrc_post >> $INSTALLDIR/.bashrc

git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

#installing ZSH
sudo apt -y install zsh
sudo apt-get -y install powerline fonts-powerline

git clone https://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh

cp ~/.oh-my-zsh/templates/zshrc.zsh-template ~/.zshrc
sed -i 's/ZSH_THEME="robbyrussell"/ZSH_THEME="agnoster"/g' ~/.zshrc

chsh -s /bin/zsh

#zsh higlighter 
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git "$HOME/.zsh-syntax-highlighting" --depth 1
cat $PWD/.zshrc_post >> $INSTALLDIR/.zshrc

#install Snap packages
sudo apt -y install snapd
sudo snap install snap-store
sudo snap install hi
sudo snap install bpytop
sudo snap connect bpytop:mount-observe
sudo snap connect bpytop:network-control
sudo snap connect bpytop:hardware-observe
sudo snap connect bpytop:system-observe
sudo snap connect bpytop:process-control
sudo snap connect bpytop:physical-memory-observe

#install docker support
sudo apt -y install apt-transport-https ca-certificates curl software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
sudo apt update
sudo apt -y install docker-ce

#install Emote snap package 🤞
sudo snap install emote
