#!/bin/bash
INSTALLDIR=${1:-$HOME}

sudo add-apt-repository ppa:jonathonf/vim
sudo apt update && sudo apt -y upgrade
# install dependencies
sudo apt-get -y install vim git curl fonts-powerline tmux ncdu

ln -s $PWD/.bash_aliases $INSTALLDIR/.bash_aliases 2> /dev/null
ln -s $PWD/.vimrc $INSTALLDIR/.vimrc 2> /dev/null
ln -s $PWD/.vim $INSTALLDIR/.vim 2> /dev/null
ln -s $PWD/.tmux.conf $INSTALLDIR/.tmux.conf 2> /dev/null

if [ ! -d "~/.vim/bundle/Vundle.vim" ]; then
	git submodule add -f https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
fi

vim +PluginInstall +qall

cat $PWD/.bashrc_post >> $INSTALLDIR/.bashrc

git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

# git settings
git config --global core.editor "vim"

#installing ZSH
sudo apt -y install zsh
sudo apt-get -y install powerline fonts-powerline

git clone https://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh

cp ~/.oh-my-zsh/templates/zshrc.zsh-template ~/.zshrc
sed -i 's/ZSH_THEME="robbyrussell"/ZSH_THEME="agnoster"/g' ~/.zshrc

chsh -s /bin/zsh

#zsh higlighter 
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git "$HOME/.zsh-syntax-highlighting" --depth 1
cat $PWD/.zshrc_post >> $INSTALLDIR/.zshrc

#install Snap packages
sudo snap install hi
sudo snap install bpytop
sudo snap connect bpytop:mount-observe
sudo snap connect bpytop:network-control
sudo snap connect bpytop:hardware-observe
sudo snap connect bpytop:system-observe
sudo snap connect bpytop:process-control
sudo snap connect bpytop:physical-memory-observe
