#!/bin/bash
INSTALLDIR=${1:-$HOME}

sudo add-apt-repository ppa:jonathonf/vim
sudo apt update && sudo apt -y upgrade
# install dependencies
sudo apt-get -y install vim git curl fonts-powerline tmux

ln -s $PWD/.bash_aliases $INSTALLDIR/.bash_aliases 2> /dev/null
ln -s $PWD/.vimrc $INSTALLDIR/.vimrc 2> /dev/null
ln -s $PWD/.vim $INSTALLDIR/.vim 2> /dev/null
ln -s $PWD/.tmux.conf $INSTALLDIR/.tmux.conf 2> /dev/null

if [ ! -d "~/.vim/bundle/Vundle.vim" ]; then
	git submodule add -f https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
fi

vim +PluginInstall +qall

cat $PWD/.bashrc_post >> $INSTALLDIR/.bashrc

git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

# git settings
git config --global core.editor "vim"
